---
title: "Q4_EDA"
author: "Brian Wimmer"
date: "2022-12-03"
output: html_document
---
```{r}
# Load libraries
library(ggplot2)
library(tidyverse)
library(psych) 
library(dplyr)
library(arsenal)
library(gridExtra)
library(grid)
```


```{r}
# Load data

# Edy Playlist 
edy <- read.csv('/Users/brianwimmer/Desktop/Georgetown/ANLY 511/Final Project/edyPlaylist.csv')
```

```{r}
# cleaning for EDA purposes

# remove full date from track.album.release_date, keep only the year
edy$track.album.release_date <- substr(edy$track.album.release_date, 0, 4)

# convert track.album.release date to numeric
edy$track.album.release_date <- as.numeric(edy$track.album.release_date)

# doing this may not be necessary, but incase we want it to make numbers seem smaller
# convert duration_ms to duration_s (milliseconds to seconds)
edy$track.duration_ms <- edy$track.duration_ms / 1000

# round up to nearest second
edy$track.duration_ms <- round(edy$track.duration_ms, digits = 0)

# rename duration_ms to duration_s
names(edy)[6] ="track.duration_s"

# create decade column for EDA
edy <- edy %>% 
  mutate(
    decade = case_when(
      track.album.release_date >= 1950 & track.album.release_date < 1960    ~ "1950s",
      track.album.release_date >= 1960 & track.album.release_date < 1970  ~ "1960s",
      track.album.release_date >= 1970 & track.album.release_date < 1980  ~ "1970s",
      track.album.release_date >= 1980 & track.album.release_date < 1990   ~ "1980s",
      track.album.release_date >= 1990 & track.album.release_date < 2000   ~ "1990s",
      track.album.release_date >= 2000 & track.album.release_date < 2010   ~ "2000s",
      track.album.release_date >= 2010 & track.album.release_date < 2020   ~ "2010s",
      track.album.release_date >= 2020    ~ "2020s"))
```

```{r}
# summary statistics of columns 3, 4, 6:15 
summary(edy[c(3,4,6:15)])
```


```{r}
# Histograms for non-audio feature variables 

# color pallete (3rd down with 12 colors): https://stackoverflow.com/questions/57153428/r-plot-color-combinations-that-are-colorblind-accessible

# track.album.release_date
date.hist <- ggplot(edy, aes(x=track.album.release_date))+
  geom_histogram(binwidth = 2, color="black", fill="#88ccee")+
  labs(title="Distribution of Release Date",x="Year", y = "Count",
              caption = "Figure 4.1: Histogram of Songs by Year")+
  scale_x_continuous(breaks=c(1950,1960,1970,1980,1990,2000,2010,2020))+
  scale_y_continuous(breaks=seq(0,150,25))+
  annotate("text", x=1958, y=125, label= "mean = 2005")+
  theme(plot.title = element_text(hjust = 0.5), plot.caption = element_text(hjust = 0.5))
date.hist

# track.popularity
popularity.hist <- ggplot(edy, aes(x=track.popularity))+
  geom_histogram(binwidth = 5, color="black", fill="#332288")+
  labs(title="Distribution of Song Popularity",x="Popularity", y = "Count",
              caption = "Figure 4.1: Histogram of Songs by Popularity")+
  scale_x_continuous(breaks=seq(0,90,10))+
  scale_y_continuous(breaks=seq(0,125,25))+
  annotate("text", x=3, y=100, label= "mean = 53")+
  theme(plot.title = element_text(hjust = 0.5), plot.caption = element_text(hjust = 0.5))
popularity.hist

# track.duration_s
duration.hist <- ggplot(edy, aes(x=track.duration_s))+
  geom_histogram(binwidth = 30, color="black", fill="#882255")+
  labs(title="Distribution of Song Duration (seconds)",x="Duration (in seconds)", y = "Count",
              caption = "Figure 4.1: Histogram of Songs by Duration (in seconds")+
  scale_x_continuous(breaks=seq(0,900,60))+
  scale_y_continuous(breaks=seq(0,250,50))+
  annotate("text", x=90, y=225, label= "mean = 246")+
  theme(plot.title = element_text(hjust = 0.5), plot.caption = element_text(hjust = 0.5))
duration.hist

#grid.arrange(date.hist, popularity.hist, nrow = 2, bottom=textGrob("Figure 4.1: Histograms of Danceability by Country", gp = gpar(fontsize = 9)))
```

```{r}
# Histograms for audio feature variables

# color pallete (3rd down with 12 colors): https://stackoverflow.com/questions/57153428/r-plot-color-combinations-that-are-colorblind-accessible

# danceability
dance.hist <- ggplot(edy, aes(x=danceability))+
  geom_histogram(binwidth = .1, color="black", fill="#cc6677")+
  labs(title="Distribution of Danceability",x="Danceability", y = "Count")+
  scale_x_continuous(breaks=c(0.25,0.50,0.75,1.00))+
  scale_y_continuous(breaks=seq(0,200,50))+
  annotate("text", x=0.125, y=200, label= "mean = 0.55")+
  theme(plot.title = element_text(hjust = 0.5))
dance.hist

# energy
energy.hist <- ggplot(edy, aes(x=energy))+
  geom_histogram(binwidth = .1, color="black", fill="#aa4499")+
  labs(title="Distribution of Energy",x="Energy", y = "Count")+
  scale_x_continuous(breaks=c(0.00,0.25,0.50,0.75,1.00))+
  scale_y_continuous(breaks=seq(0,200,50))+
  annotate("text", x=0, y=200, label= "mean = 0.62")+
  theme(plot.title = element_text(hjust = 0.5))
energy.hist

# loudness
loud.hist <- ggplot(edy, aes(x=loudness))+
  geom_histogram(bins = 10, color="black", fill="#661100")+
  labs(title="Distribution of Loudness",x="Loudness", y = "Count")+
  scale_y_continuous(breaks=seq(0,375,75))+
  annotate("text", x=-35, y=375, label= "mean = -8.62")+
  theme(plot.title = element_text(hjust = 0.5))
loud.hist

# speechiness
speech.hist <- ggplot(edy, aes(x=speechiness))+
  geom_histogram(binwidth = .05, color="black", fill="#ddcc77")+
  labs(title="Distribution of Speechiness",x="Speechiness", y = "Count")+
  scale_x_continuous(breaks=c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5))+
  annotate("text", x=0.5, y=750, label= "mean = 0.07")+
  theme(plot.title = element_text(hjust = 0.5))
speech.hist

# acousticness
acous.hist <- ggplot(edy, aes(x=acousticness))+
  geom_histogram(binwidth = .1, color="black", fill="#44aa99")+
  labs(title="Distribution of Acousticness",x="Acousticness", y = "Count")+
  scale_x_continuous(breaks=c(0.00, 0.25,0.50,0.75,1.00))+
  annotate("text", x=1, y=300, label= "mean = 0.33")+
  theme(plot.title = element_text(hjust = 0.5))
acous.hist

# instrumentalness
instr.hist <- ggplot(edy, aes(x=instrumentalness))+
  geom_histogram(binwidth = .1, color="black", fill="#6699cc")+
  labs(title="Distribution of Instrumentalness",x="Instrumentalness", y = "Count")+
  annotate("text", x=1, y=800, label= "mean = 0.14")+
  theme(plot.title = element_text(hjust = 0.5))
instr.hist

# liveness
live.hist <- ggplot(edy, aes(x=liveness))+
  geom_histogram(binwidth = .1, color="black", fill="#117733")+
  labs(title="Distribution of Liveness",x="Liveness", y = "Count")+
  scale_y_continuous(breaks=seq(0,500,100))+
  annotate("text", x=1, y=550, label= "mean = 0.19")+
  theme(plot.title = element_text(hjust = 0.5))
live.hist

# valence
val.hist <- ggplot(edy, aes(x=valence))+
  geom_histogram(binwidth = .1, color="black", fill="#999933")+
  labs(title="Distribution of Valence",x="Valence", y = "Count")+
  scale_y_continuous(breaks=seq(0,125,25))+
  annotate("text", x=0, y=125, label= "mean = 0.48")+
  theme(plot.title = element_text(hjust = 0.5))
val.hist

# tempo
tempo.hist <- ggplot(edy, aes(x=tempo))+
  geom_histogram(bins = 10, color="black", fill="#888888")+
  labs(title="Distribution of Tempo",x="Tempo", y = "Count")+
  scale_y_continuous(breaks=seq(0,250,50))+
  annotate("text", x=60, y=275, label= "mean = 119.87")+
  theme(plot.title = element_text(hjust = 0.5))
tempo.hist
```

```{r}
# Histograms arranged in 1x2 grids, 9 variables so will cut instrumentalness and would print it on its own
# Leaving caption mostly blank until we decide which grid preference we prefer
# mean labels would need to be fixed if we go this route

grid.arrange(dance.hist, energy.hist, ncol = 2, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(speech.hist, acous.hist, ncol = 2, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(live.hist, val.hist, ncol = 2, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(loud.hist, tempo.hist, ncol = 2, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

instr.hist
```

```{r}
# Histograms arranged in 1x3 grids, 9 variables 
# Leaving caption mostly blank until we decide which grid preference we prefer
# mean labels and titles would need to be fixed if we go this route

grid.arrange(dance.hist, energy.hist, speech.hist,ncol = 3, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(acous.hist, instr.hist, live.hist,ncol = 3, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(val.hist, loud.hist, tempo.hist,ncol = 3, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))
```


```{r}
# Histograms arranged in 3x1 grids, 9 variables 
# Leaving caption mostly blank until we decide which grid preference we prefer
# mean labels would need to be fixed if we go this route

grid.arrange(dance.hist, energy.hist, speech.hist,nrow = 3, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(acous.hist, instr.hist, live.hist,nrow = 3, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))

grid.arrange(val.hist, loud.hist, tempo.hist,nrow = 3, bottom=textGrob("Figure 4.1: Histograms ...", gp = gpar(fontsize = 9)))
```

```{r}
# bar plot of decade variable 

# get counts
#table(edy['decade'])
# 1950s 1960s 1970s 1980s 1990s 2000s 2010s 2020s 
#    2     8    43    67    83   331   392    50 

decade.totals <- data.frame(Decade=c("1950s","1960s","1970s","1980s",
                                     "1990s","2000s","2010s","2020s"),
                     Count=c(2,8,43,67,83,331,392,50))

ggplot(decade.totals, aes(x=Decade, y=Count, fill=Decade)) + 
       geom_bar(stat="identity")+
       labs(title="Number of Songs by Decade", x="Decade", y = "Count", 
       caption = "Figure 4.1: Barplot of Songs by Decade")+
       scale_fill_manual(values=c("#888888", "#DDCC77", "#AA4499", "#332288", 
                                  "#CC6677", "#88CCEE", "#44AA99", "#117733"))+
       theme(plot.title = element_text(hjust = 0.5), plot.caption = element_text(hjust = 0.5))+
       geom_text(aes(label = Count), vjust = -0.2)
```

```{r}
# pie chart for decade variable 
# percentage values can be removed

ggplot(decade.totals, aes(x="", y=Count, fill=Decade)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(aes(x=1.65, label = paste0(round((Count/976)*100), "%")), position = position_stack(vjust=0.5)) +
  labs(title="Proportion of Songs by Decade", fill = "Decade", x=NULL, y=NULL, caption= "Figure 4.1: Pie Chart of Songs by Decade") +
  theme_classic() +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_manual(values=c("#888888", "#DDCC77", "#AA4499", "#332288", 
                                  "#CC6677", "#88CCEE", "#44AA99", "#117733"))+
       theme(plot.title = element_text(hjust = 0.5), plot.caption = element_text(hjust = 0.5))
```




















